name: misfitunited
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # --- GAME ENGINE ---
  flame: ^1.20.0        # Jantung permainan kartu/match
  
  # --- LOGIC & STATE ---
  flutter_bloc: ^8.1.0  # Otak aplikasi (memisahkan UI & Logic)
  equatable: ^2.0.5     # Pembantu BLoC
  
  # --- UI & VISUAL ---
  google_fonts: ^6.1.0  # Font Cyberpunk
  flutter_animate: ^4.5.0 # Efek animasi UI (Glow/Slide)
  gap: ^3.0.0           # Pengganti SizedBox yang lebih rapi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Pastikan spasi (indentasi) pas seperti ini:
  assets:
    - assets/images/
